version: 0.2

env:
  variables:
    TARGET_S3_BUCKET: "YOUR_S3_BUCKET_NAME"
    CLOUDFRONT_DIST_ID: "YOUR_CLOUDFRONT_DIST_ID"

phases:
  install:
    commands:
      - echo "Simple install phase test" 
  pre_build: # pre_buildフェーズのコメントアウトを解除
    commands:
      - echo "Pre-build phase: Git LFSオブジェクトを取得します..."
      - git lfs pull
      - echo "Git LFSオブジェクトの取得が完了しました。"

  # build:
  #   commands:
  #     - echo "Build phase: S3バケット ($TARGET_S3_BUCKET) への同期処理を開始します..."
  #     - aws s3 sync . s3://$TARGET_S3_BUCKET/ --delete --exclude ".git/*" --exclude ".gitattributes" --exclude ".lfsconfig" --exclude "buildspec.yml" --exclude "README.md" --exclude "README.txt"
  #     - echo "S3バケットへの同期が完了しました。"
  #     - |
  #       if [ -n "$CLOUDFRONT_DIST_ID" ] && [ "$CLOUDFRONT_DIST_ID" != "null" ] && [ "$CLOUDFRONT_DIST_ID" != "NONE" ]; then
  #         echo "CloudFrontキャッシュ ($CLOUDFRONT_DIST_ID) の無効化を開始します。"
  #         aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DIST_ID" --paths "/*"
  #         echo "CloudFrontキャッシュの無効化をリクエストしました。"
  #       else
  #         echo "CLOUDFRONT_DIST_IDが設定されていないため、キャッシュの無効化はスキップします。"
  #       fi

  # post_build:
  #   commands:
  #     - echo "Post-build phase: ビルドプロセスが完了しました。"

