version: 0.2

phases:
  pre_build:
    commands:
      - echo "No build phase"
  build:
    commands:
      - echo "No build commands"
  post_build:
    commands:
      - echo "No post_build phase"

artifacts:
  files:
  - '**/*'   # アップロードするファイル
  discard-paths: yes  # ファイルのパス構造を保存したくない場合は "yes" にします。
