version: 0.2

env:
  variables:
    TARGET_S3_BUCKET: "YOUR_S3_BUCKET_NAME"
    CLOUDFRONT_DIST_ID: "YOUR_CLOUDFRONT_DIST_ID"

phases:
  install:
    commands:

  pre_build:
    commands:
      - git lfs pull

  build:
    commands:
      - aws s3 sync . s3://$TARGET_S3_BUCKET/ --delete --exclude ".git/*" --exclude ".gitattributes" --exclude ".lfsconfig" --exclude "buildspec.yml" --exclude "README.md" --exclude "README.txt"
      - |
        if [ -n "$CLOUDFRONT_DIST_ID" ] && [ "$CLOUDFRONT_DIST_ID" != "null" ] && [ "$CLOUDFRONT_DIST_ID" != "NONE" ]; then
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DIST_ID" --paths "/*"
        fi

  post_build:
    commands:
      - echo "Build process complete."

