version: 0.2

env:
  variables:
    TARGET_S3_BUCKET: "YOUR_S3_BUCKET_NAME" # CodeBuildプロジェクトの環境変数で設定してください
    CLOUDFRONT_DIST_ID: "YOUR_CLOUDFRONT_DIST_ID" # CodeBuildプロジェクトの環境変数で設定してください

phases:
  install:
    commands:
      # Ubuntuベースのイメージを想定して apt-get を使用
      - apt-get update -y
      - apt-get install -y git-lfs
      - git lfs install

  pre_build:
    commands:
      - git lfs pull

  build:
    commands:
      - aws s3 sync . s3://$TARGET_S3_BUCKET/ --delete --exclude ".git/*" --exclude ".gitattributes" --exclude ".lfsconfig" --exclude "buildspec.yml" --exclude "README.md" --exclude "README.txt"
      - |
        if [ -n "$CLOUDFRONT_DIST_ID" ] && [ "$CLOUDFRONT_DIST_ID" != "null" ] && [ "$CLOUDFRONT_DIST_ID" != "NONE" ]; then
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DIST_ID" --paths "/*"
        fi

  post_build:
    commands:
      - echo "Build process complete." # 非常にシンプルな完了メッセージ（コロンなし）

