version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Zip the artifact...
      - |
        if [ "$ENVIRONMENT" = "prd" ]; then
          zip -r production-function.zip .
        elif [ "$ENVIRONMENT" = "stg" ]; then
          zip -r staging-function.zip .
        else
          echo "Environment not defined or incorrect"
          exit 1
        fi
artifacts:
  files:
    - 'staging-function.zip'
    - 'production-function.zip'
